import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";

const NOW = sql`(datetime('now'))`;

export const superAdminsTable = sqliteTable("super_admins", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  phone: text("phone").unique(),
  passwordHash: text("password_hash").notNull(),
  avatar: text("avatar"),
  plainPassword: text("plain_password"),
  isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
  createdAt: text("created_at").notNull().default(NOW),
});

export const plansTable = sqliteTable("plans", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  description: text("description"),
  price: text("price").notNull(),
  billingCycle: text("billing_cycle").notNull().default("monthly"),
  maxUsers: integer("max_users").notNull().default(5),
  trialDays: integer("trial_days").notNull().default(0),
  validityDays: integer("validity_days").notNull().default(30),
  features: text("features", { mode: "json" }).$type<string[]>(),
  maxVouchersPerMonth: integer("max_vouchers_per_month"),
  maxItems: integer("max_items"),
  maxParties: integer("max_parties"),
  isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
  sortOrder: integer("sort_order").notNull().default(0),
  packageConfig: text("package_config"),
  createdAt: text("created_at").notNull().default(NOW),
});

export const businessesTable = sqliteTable("businesses", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  businessCode: text("business_code").notNull().unique(),
  gstin: text("gstin"),
  pan: text("pan"),
  address: text("address"),
  city: text("city"),
  state: text("state"),
  stateCode: text("state_code"),
  pincode: text("pincode"),
  phone: text("phone"),
  email: text("email"),
  businessType: text("business_type"),
  logo: text("logo"),
  planId: integer("plan_id"),
  activeVoucherId: integer("active_voucher_id"),
  planStartDate: text("plan_start_date"),
  planExpiresAt: text("plan_expires_at"),
  isTrial: integer("is_trial", { mode: "boolean" }).notNull().default(false),
  status: text("status").notNull().default("active"),
  financialYearStart: text("financial_year_start").default("04-01"),
  currency: text("currency").default("INR"),
  invoicePrefix: text("invoice_prefix").default("SI"),
  creditNotePrefix: text("credit_note_prefix").default("CN"),
  billPrefix: text("bill_prefix").default("PB"),
  debitNotePrefix: text("debit_note_prefix").default("DN"),
  serialNumberMode: text("serial_number_mode").default("auto"),
  numberSeries: integer("number_series").default(1),
  numberDigits: integer("number_digits").default(4),
  numberSeparator: text("number_separator").default("-"),
  bankName: text("bank_name"),
  bankAccount: text("bank_account"),
  bankIfsc: text("bank_ifsc"),
  bankBranch: text("bank_branch"),
  signatoryName: text("signatory_name"),
  invoiceFooter: text("invoice_footer"),
  siStartNumber: integer("si_start_number").default(1),
  cnStartNumber: integer("cn_start_number").default(1),
  pbStartNumber: integer("pb_start_number").default(1),
  dnStartNumber: integer("dn_start_number").default(1),
  referralCode: text("referral_code").unique(),
  referredBy: text("referred_by"),
  referralCount: integer("referral_count").notNull().default(0),
  referralRewardCount: integer("referral_reward_count").notNull().default(0),
  referralRewardedAt: text("referral_rewarded_at"),
  bonusDaysAdded: integer("bonus_days_added").notNull().default(0),
  printShowPrefix: integer("print_show_prefix", { mode: "boolean" }).default(true),
  printShowSeries: integer("print_show_series", { mode: "boolean" }).default(true),
  printShowZeros: integer("print_show_zeros", { mode: "boolean" }).default(true),
  createdAt: text("created_at").notNull().default(NOW),
});

export const appSettingsTable = sqliteTable("app_settings", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  key: text("key").notNull().unique(),
  value: text("value"),
  updatedAt: text("updated_at").notNull().default(NOW),
});

export const licenseVouchersTable = sqliteTable("license_vouchers", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  code: text("code").notNull().unique(),
  planId: integer("plan_id").notNull(),
  validityDays: integer("validity_days").notNull().default(30),
  sellingPrice: text("selling_price"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  generatedBy: integer("generated_by"),
  redeemedByBusinessId: integer("redeemed_by_business_id"),
  redeemedAt: text("redeemed_at"),
  createdAt: text("created_at").notNull().default(NOW),
});
