import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";

const NOW = sql`(datetime('now'))`;

export const vouchersTable = sqliteTable("vouchers", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  businessId: integer("business_id").notNull(),
  voucherType: text("voucher_type").notNull(),
  voucherNumber: text("voucher_number").notNull(),
  date: text("date").notNull(),
  partyId: integer("party_id").notNull(),
  billingAddress: text("billing_address"),
  useShippingAddress: integer("use_shipping_address", { mode: "boolean" }).default(false),
  shippingAddress: text("shipping_address"),
  subTotal: text("sub_total").default("0"),
  totalDiscount: text("total_discount").default("0"),
  taxableAmount: text("taxable_amount").default("0"),
  totalCgst: text("total_cgst").default("0"),
  totalSgst: text("total_sgst").default("0"),
  totalIgst: text("total_igst").default("0"),
  totalTax: text("total_tax").default("0"),
  transportCharges: text("transport_charges").default("0"),
  transportName: text("transport_name"),
  roundOff: text("round_off").default("0"),
  grandTotal: text("grand_total").notNull().default("0"),
  paidAmount: text("paid_amount").default("0"),
  status: text("status").notNull().default("posted"),
  notes: text("notes"),
  termsAndConditions: text("terms_and_conditions"),
  linkedVoucherId: integer("linked_voucher_id"),
  isInterState: integer("is_inter_state", { mode: "boolean" }).default(false),
  placeOfSupply: text("place_of_supply"),
  referenceNumber: text("reference_number"),
  dueDate: text("due_date"),
  customFields: text("custom_fields", { mode: "json" }),
  createdAt: text("created_at").notNull().default(NOW),
  deletedAt: text("deleted_at"),
});

export const voucherItemsTable = sqliteTable("voucher_items", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  voucherId: integer("voucher_id").notNull(),
  itemId: integer("item_id"),
  itemName: text("item_name").notNull(),
  description: text("description"),
  hsnCode: text("hsn_code"),
  quantity: text("quantity").notNull(),
  unit: text("unit"),
  rate: text("rate").notNull(),
  discount: text("discount").default("0"),
  discountType: text("discount_type").default("percent"),
  taxableAmount: text("taxable_amount").notNull(),
  taxRateId: integer("tax_rate_id"),
  taxRate: text("tax_rate").default("0"),
  cgst: text("cgst").default("0"),
  sgst: text("sgst").default("0"),
  igst: text("igst").default("0"),
  taxAmount: text("tax_amount").default("0"),
  total: text("total").notNull(),
  customFields: text("custom_fields", { mode: "json" }),
});
