export type Lang = "en" | "hi";

const KEY = "erp_lang";

export function getLang(): Lang {
  return (localStorage.getItem(KEY) as Lang) || "en";
}
export function setLang(lang: Lang) {
  localStorage.setItem(KEY, lang);
  window.dispatchEvent(new CustomEvent("lang-change"));
}
export function toggleLang() {
  setLang(getLang() === "en" ? "hi" : "en");
}

export const T: Record<Lang, Record<string, string>> = {
  en: {
    // ── Nav ──
    dashboard: "Dashboard",
    sales: "Sales",
    invoices: "Invoices",
    creditNotes: "Credit Notes",
    purchases: "Purchases",
    bills: "Bills",
    debitNotes: "Debit Notes",
    payments: "Payments",
    receipts: "Receipts",
    outstanding: "Outstanding",
    inventory: "Inventory",
    accounting: "Accounting",
    partyLedger: "Party Ledger",
    trialBalance: "Trial Balance",
    receivables: "Receivables",
    payables: "Payables",
    gstReports: "GST Reports",
    gstr1: "GSTR-1",
    gstr3b: "GSTR-3B",
    masters: "Masters",
    customers: "Customers",
    suppliers: "Suppliers",
    allParties: "All Parties",
    items: "Items",
    units: "Units",
    hsnCodes: "HSN Codes",
    taxRates: "Tax Rates",
    states: "States",
    myPlan: "My Plan",
    users: "Users",
    settings: "Settings",
    signOut: "Sign Out",
    connected: "Connected",
    offline: "Offline",
    setLocation: "Set Location",
    dataFolder: "Set Data Folder",
    language: "Language",
    cashBank: "Cash & Bank",
    cashBankAccounts: "Accounts",
    expenseHeads: "Expense Heads",
    expenses: "Expenses",
    contraEntry: "Contra Entry",
    cashBankStatement: "Statement",
    loginActivity: "Login Activity",
    allUsers: "All Users",
    buyers: "Buyers",
    businesses: "Businesses",
    plans: "Plans",
    licenseVouchers: "License Vouchers",
    techSupportAccounts: "Tech Support Accounts",
    appSettings: "App Settings",

    // ── Common actions ──
    save: "Save",
    saving: "Saving...",
    cancel: "Cancel",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    remove: "Remove",
    change: "Change",
    search: "Search...",
    refresh: "Refresh",
    submit: "Submit",
    create: "Create",
    creating: "Creating...",
    upload: "Upload",
    download: "Download",
    backup: "Backup",
    restore: "Restore",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    close: "Close",
    back: "Back",
    loading: "Loading...",
    noData: "No data found",
    error: "Error",
    success: "Success",

    // ── Common labels ──
    name: "Name",
    email: "Email",
    phone: "Phone",
    password: "Password",
    newPassword: "New Password",
    currentPassword: "Current Password",
    confirmPassword: "Confirm Password",
    role: "Role",
    status: "Status",
    date: "Date",
    amount: "Amount",
    type: "Type",
    notes: "Notes",
    address: "Address",
    city: "City",
    state: "State",
    pincode: "Pincode",

    // ── Item combobox ──
    itemSearchPlaceholder: "Type item name or search...",
    itemWillBeAdded: "will be added to master on save",
    newItemWillBeAdded: "new item, will be auto-added to master on save",

    // ── Voucher form ──
    binLoadError: "Failed to load document from bin — please try again",
    itemMasterSaveError: "could not be saved to master",
    voucherSavedWithErrors: "Voucher saved, but some items could not be added to master",
    duplicateVoucherNumber: "Voucher number already exists",
    manualModeVoucherRequired: "Voucher number is required in manual mode",
    partyCreateFailed: "Could not create party",
    offlinePartyCreate: "You are offline — please connect to internet first, then create a new party. Select an existing party or save as draft.",
    dragToResize: "Drag to resize items area",

    // ── Location modal ──
    setDeviceLocation: "Set Device Location",
    locationSavedOnDevice: "This location will be saved on this device. When working offline, it will be attached to each draft so you know where the data came from when it syncs.",
    detectingGps: "Detecting via GPS...",
    autoDetectGps: "Auto-Detect via GPS",
    locationName: "Location Name",
    locationNamePlaceholder: "e.g. Delhi Branch, Godown No. 2, Main Office",
    locationNameRequired: "Please enter a location name",
    currentlySet: "Currently set:",
    locationSaved: "Saved!",

    // ── Column customizer ──
    adjustColumns: "Adjust columns",
    showHideColumns: "Show / Hide Columns",
    showAllColumns: "Show all columns",

    // ── Password drawer ──
    passwordNotSet: "not set",
    hidePassword: "Hide",
    showPassword: "Show",
    copyPassword: "Copy",
    noData2: "No data",
    noUsers: "No users",

    // ── Users page ──
    deleteUserConfirm: "Are you sure you want to delete this user?",
    noUsersFound: "No users found",
    newPasswordHint: "New Password (leave blank to keep unchanged)",
    loginPinHint: "for users sharing the same email and password",
    enterNewPin: "Enter new PIN (leave blank to keep unchanged)",
    editRecordsRight: "Permission to edit records",
    deleteRecordsRight: "Permission to delete records",

    // ── Admin Settings ──
    imageTooLarge15: "Image must be smaller than 1.5MB",
    passwordMismatch: "New password and confirm password do not match",
    currentPasswordRequired: "Current password is required",
    profileUpdated: "Profile updated successfully!",
    profileUpdateError: "Error updating profile",
    fingerprintAlreadyRegistered: "This fingerprint is already registered!",
    fingerprintCancelled: "Fingerprint setup was cancelled",
    fingerprintError: "Error during fingerprint setup",
    fingerprintSettingUp: "Setting up...",
    registerFingerprint: "Register Fingerprint",
    deleteFingerprintConfirm: "Old fingerprint will be deleted. Confirm?",
    fingerprintRemoved: "Old fingerprint removed. Use 'Register Fingerprint' to add again.",
    fingerprintResetError: "Error during reset",
    resetReRegister: "Reset / Re-register",
    fingerprintTimeoutHint: "If you see 'timed out' or 'not allowed' error, first Reset, then register again on the same device/browser.",
    logoTooLarge500: "Logo must be smaller than 500KB",
    uploadPhoto: "Upload Photo",
    changePhoto: "Change Photo",
    uploadLogo: "Upload Logo",
    changeLogo: "Change Logo",
    mobileForLogin: "Mobile Number (used for login)",
    mobileLoginHint: "This number will be used for Tech Login",
    changePassword: "Change Password",
    leaveBlankMobileOnly: "(leave blank to only update mobile)",
    oldPassword: "Old password",
    newPasswordMin: "New password (min 6 chars)",
    confirmNewPassword: "Confirm new password",
    saveProfile: "Save Profile",
    techLoginMyProfile: "Tech Login — My Profile",
    techLoginProfileDesc: "Update Tech Login mobile number and password here.",
    fingerprintRegistered: "Fingerprint registered! You can now view all user passwords from the login page using fingerprint.",
    printFooterTitle: "Print Footer (On Every Invoice / PDF)",
    printFooterDesc: "This text and logo will appear at the bottom of all businesses' prints/PDFs.",
    printFooterLineHint: "This line will appear at the very bottom of the print",

    // ── Business Settings ──
    offlineDraftsFolderDesc: "Offline drafts will be saved as JSON files in this folder",
    settingsSaved: "Settings saved successfully!",
    firmIdentity: "Firm Identity (shown on invoice)",
    voucherRedeemError: "Voucher could not be redeemed",
    repairConfirm: "This will recalculate paidAmount and status for all vouchers. Proceed?",
    vouchersFixed: "vouchers fixed",
    repairFailed: "Repair failed — check browser console",
    chooseFolder: "Choose Folder",
    businessTypeInfo_pharmacy: "Invoice will include: Drug License, Batch No, Expiry Date, MRP fields",
    businessTypeInfo_electronics: "Invoice will include: Serial No, Model No, Brand, Warranty fields",
    businessTypeInfo_fabric: "Invoice will include: Color, Design, Width, Composition fields",
    businessTypeInfo_restaurant: "Invoice will include: Table No, Cover Count, Waiter Name fields",
    businessTypeInfo_auto_parts: "Invoice will include: Vehicle Reg No, Vehicle Model, Part No fields",
    businessTypeInfo_jewellery: "Invoice will include: Hallmark No, Purity, Weight, Making Charges fields",
    businessTypeInfo_construction: "Invoice will include: Project Name, Work Order No, Site fields",
    businessTypeInfo_grocery: "Invoice will include: Batch No, Expiry Date fields",
    businessTypeInfo_hardware: "Invoice will include: Brand, Model No fields",
    showPrefix: "Show Prefix (SI, CN, PB, DN)",
    showPrefixSub: "SI/CN/PB/DN prefix shown in print",
    showSeries: "Show Series Number (1, 2, 3...)",
    showSeriesSub: "Only works when series > 1",
    showLeadingZeros: "Show Leading Zeros (0001 → 1)",
    showLeadingZerosSub: "When OFF, shows 5 instead of 00005",

    // ── Super Admins ──
    allFieldsRequired: "All fields are required",
    passwordMinChars: "Password must be at least 6 characters",
    deleteSuperAdminConfirm: "Are you sure? This super admin will be removed.",
    newAdmin: "New Admin",
    superAdminDesc: "Super admin accounts with full system access",
    createNewSuperAdmin: "Create New Super Admin",
    fullName: "Full name",
    atLeast6Chars: "At least 6 characters",
    noSuperAdminFound: "No super admins found",
    superAdminWarning: "Note: Super admins have full platform access — only add trusted tech support team members here.",
    creating2: "Creating...",
    createBtn: "Create",

    // ── Voucher Bin ──
    binPageDesc: "Deleted vouchers — restore or permanently delete",
    voucherRestored: "Voucher restored successfully!",
    voucherPermanentlyDeleted: "Voucher permanently deleted.",
    binEmpty: "Bin is empty",
    binEmptyDesc: "No deleted documents",
    binHasDocuments: "document(s) in bin. Restore to bring back, or permanently delete (cannot be undone).",
    permanentlyDeleteConfirm: "Permanently delete?",
    yesDelete: "Yes, Delete",

    // ── Offline Drafts ──
    offlineDraftsDesc: "Saved when offline — submit now",
    noPendingDrafts: "No pending drafts",
    allDataSubmitted: "All data has been submitted",
    goToDashboard: "Go to Dashboard",
    submitAll: "Submit All",
    submittedToServer: "Submitted to server successfully",
    offlinePartyNotFound: "Party not found on server. Please create the party first, then submit.",
    partyIdNotResolved: "Party ID could not be resolved. Use 'Submit All' or delete the draft and create a new one.",
    offlinePartyTip: "Some vouchers have parties created offline. Use Submit All — it submits in the correct order.",

    // ── Tech Login ──
    techLoginError: "Phone or password is incorrect",
    techForgotError: "Something went wrong — please try again",
    techStaffOnly: "For authorized staff only",
    mobileOrEmail: "Mobile or email",
    forgotPassword: "Forgot password?",
    loginBtn: "Sign In",
    goToBusinessLogin: "← Go to Business Login",
    resetTechPassword: "Reset tech staff password",
    registeredMobileHint: "Enter the mobile/email linked to your account",
    chooseNewPassword: "Choose a new password",
    resetPasswordBtn: "Reset Password",
    goToLoginPage: "Go to Login Page",
    passwordResetSuccess: "Password reset successfully!",
    loginInProgress: "Signing in...",

    // ── Trial Banner ──
    trialEnded: "Trial Period Ended",
    trialEndedDesc: "Your trial period has ended. Please activate a plan to continue using the software.",
    contactTechSupport: "Contact Tech Support",
    graceWarning: "software will be locked in",
    graceWarning2: "days! Activate a plan now.",
    viewPlans: "View Plans",
    trialExpiredBanner: "Trial period ended — activate a plan for unlimited access!",
    gracePeriod: "30 Days Grace Period —",

    // ── Referral Banner ──
    referralRewardEarned: "Referral Reward Earned!",
    referralsCompleted: "referrals completed — Referral Plan activated on your account!",
    moreReferrals: "more referrals → one more reward!",

    // ── Subscription ──
    currentPlanBadge: "Your Current Plan",
    perMonth: "/month",
    perYear: "/year",
    daysValidity: "days validity",
    invoicesPerMonth: "invoices/month",
    inTrial: "On trial",
    paidPlanActive: "Paid plan active",
    shareCode: "Share",
    register5: "5 people register",
    theyEnterCode: "They enter your code during registration",
    getReferralPlan: "Get Referral Plan!",
    planAutoActivate: "Your plan auto-activates — congratulations!",
    voucherRedeemFailed: "Voucher could not be redeemed",

    // ── Activity ──
    allLoginsDesc: "All logins, active users, and GPS locations",
    timeAgoSuffix: "ago",

    // ── Admin Vouchers ──
    cancelVoucherConfirm: "Are you sure you want to cancel this voucher?",
    buyerCodeInstructions: "Give these codes to the buyer. The buyer will enter the code on the 'My Plan' page.",

    // ── Admin Businesses ──
    searchPartyPlaceholder: "Search party name...",
    selectPartyFirst: "Select a party first",
    deletePartyTransactions: "Delete transactions for",
    howManyDaysToAdd: "How many days to add?",
    days: "days",
    daysAddedSuccess: "days added successfully!",
    bonusDaysAlready: "Already has bonus days added",
    cleanupOnlyVouchersPayments: "only vouchers and payments will be deleted. Customers, suppliers, items, units, and tax rates will remain safe.",
    cleanupFullBusiness: "Full Business Clean",
    cleanupOneParty: "One Party Clean",
    cleanupDone: "Cleanup complete!",
    cleanupWillDelete: "This will be deleted:",
    typeDeleteToConfirm: 'Type "DELETE" to confirm',
    cleanAllData: "Clean All Data",
    noPartyFound: "No party found",
    selectPartyToClean: "Select a party below — only that party's vouchers and payments will be deleted.",
    noUsersInBusiness: "No users in this business",
    assignRights: "Assign Rights",
    perPlanModules: "(modules available as per plan)",
    allModules: "(all modules)",

    // ── Admin Vouchers ──
    deleteAll: "Delete All",
    selectPlanFolder: "Select a plan folder from the left",
    noVouchersInFolder: "No vouchers in this folder",
    max50AtOnce: "Max 50 at a time",
    afterPlanActivation: "After plan activation",
    sellingPriceNote: "Amount charged to buyer — for record keeping",
    vouchersGenerated: "voucher(s) generated!",
    voucherEditTitle: "Edit Voucher",
    validityDaysNote: "How many days after plan activation",

    // ── Business / Admin Settings ──
    removeFolderBtn: "Remove",
    changeFolderBtn: "Change",
    offlineDraftsChromeOnly: "Offline folder save only works on Chrome/Edge desktop. On mobile, drafts are saved in localStorage.",
    offlineDataFolder: "Offline Data Folder",
    logoTooLarge500kb: "Logo must be smaller than 500KB",
    fingerprintSetupDesc: "Register your fingerprint — then on the login page you can view all user passwords using fingerprint only (no password needed).",
    voucherEditCurrentStatus: "Current status:",
    repairVouchersBtn: "Recalculate Voucher Balances",

    // ── Admin Users ──
    passwordMin4: "Password must be at least 4 characters",
    passwordResetDone: "Password reset successfully ✓",

    // ── API / Session ──
    sessionInvalidated: "Your session was terminated due to a login from another location. Please log in again.",

    // ── locationStore ──
    gpsNotSupported: "GPS is not supported in your browser",
    gpsAccessDenied: "GPS access denied — please type your location manually",
  },

  hi: {
    // ── Nav ──
    dashboard: "Dashboard",
    sales: "Bikri",
    invoices: "Invoice",
    creditNotes: "Credit Note",
    purchases: "Kharidi",
    bills: "Bill",
    debitNotes: "Debit Note",
    payments: "Bhugtan",
    receipts: "Receipt",
    outstanding: "Baki Raashi",
    inventory: "Maal / Stock",
    accounting: "Hisaab",
    partyLedger: "Party Khata",
    trialBalance: "Trial Balance",
    receivables: "Lena Hai",
    payables: "Dena Hai",
    gstReports: "GST Report",
    gstr1: "GSTR-1",
    gstr3b: "GSTR-3B",
    masters: "Master Data",
    customers: "Grahak",
    suppliers: "Supplier",
    allParties: "Sab Parties",
    items: "Items",
    units: "Units",
    hsnCodes: "HSN Codes",
    taxRates: "Tax Rates",
    states: "States",
    myPlan: "Mera Plan",
    users: "Users",
    settings: "Settings",
    signOut: "Bahar Jao",
    connected: "Juda Hua",
    offline: "Offline",
    setLocation: "Location Set Karo",
    dataFolder: "Data Folder Set Karo",
    language: "Bhasha",
    cashBank: "Cash & Bank",
    cashBankAccounts: "Accounts",
    expenseHeads: "Kharcha Heads",
    expenses: "Kharcha",
    contraEntry: "Contra Entry",
    cashBankStatement: "Statement",
    loginActivity: "Login Activity",
    allUsers: "Sab Users",
    buyers: "Buyers",
    businesses: "Businesses",
    plans: "Plans",
    licenseVouchers: "License Vouchers",
    techSupportAccounts: "Tech Support Accounts",
    appSettings: "App Settings",

    // ── Common actions ──
    save: "Save Karo",
    saving: "Save ho raha hai...",
    cancel: "Wapas",
    add: "Add Karo",
    edit: "Badlo",
    delete: "Hatao",
    remove: "Hatao",
    change: "Badlo",
    search: "Dhundho...",
    refresh: "Refresh",
    submit: "Submit Karo",
    create: "Banao",
    creating: "Ban raha hai...",
    upload: "Upload Karo",
    download: "Download",
    backup: "Backup",
    restore: "Restore",
    confirm: "Confirm",
    yes: "Haan",
    no: "Nahi",
    close: "Band Karo",
    back: "Wapas",
    loading: "Load ho raha hai...",
    noData: "Koi data nahi mila",
    error: "Error",
    success: "Sahi Hua",

    // ── Common labels ──
    name: "Naam",
    email: "Email",
    phone: "Phone",
    password: "Password",
    newPassword: "Naya Password",
    currentPassword: "Purana Password",
    confirmPassword: "Password Dobara Daalo",
    role: "Role",
    status: "Status",
    date: "Tarikh",
    amount: "Raashi",
    type: "Prakar",
    notes: "Notes",
    address: "Pata",
    city: "Sheher",
    state: "Rajya",
    pincode: "Pincode",

    // ── Item combobox ──
    itemSearchPlaceholder: "Item ka naam likho ya search karo...",
    itemWillBeAdded: "save karne par master mein add ho jayega",
    newItemWillBeAdded: "nayi item, save par master mein automatically add hogi",

    // ── Voucher form ──
    binLoadError: "Bin se document load nahi hua — dobara try karein",
    itemMasterSaveError: "master mein save nahi hua",
    voucherSavedWithErrors: "Voucher save hua, lekin kuch items master mein add nahi hue",
    duplicateVoucherNumber: "Voucher number duplicate hai",
    manualModeVoucherRequired: "Manual mode mein voucher number daalna zaroori hai",
    partyCreateFailed: "Party create nahi ho saka",
    offlinePartyCreate: "Offline hai — pehle internet se connect ho, phir naya party banao. Existing party select karo ya draft save karo.",
    dragToResize: "Drag karo items area bada karne ke liye",

    // ── Location modal ──
    setDeviceLocation: "Device Location Set Karo",
    locationSavedOnDevice: "Yeh location is device par save hogi. Offline kaam karne par har draft ke saath yeh attach ho jaayegi, taaki sync hone par pata chale data kahaan se aaya.",
    detectingGps: "GPS se detect kar rahe hain...",
    autoDetectGps: "GPS se Auto-Detect Karo",
    locationName: "Location ka Naam",
    locationNamePlaceholder: "e.g. Delhi Branch, Godown No. 2, Main Office",
    locationNameRequired: "Location naam daalo",
    currentlySet: "Abhi set hai:",
    locationSaved: "Saved!",

    // ── Column customizer ──
    adjustColumns: "Columns adjust karein",
    showHideColumns: "Columns dikhao / chhupao",
    showAllColumns: "Sab columns dikhao",

    // ── Password drawer ──
    passwordNotSet: "set nahi",
    hidePassword: "Chhupaao",
    showPassword: "Dekho",
    copyPassword: "Copy karo",
    noData2: "Koi data nahi",
    noUsers: "Koi user nahi",

    // ── Users page ──
    deleteUserConfirm: "Is user ko delete karna chahte hain?",
    noUsersFound: "Koi user nahi mila",
    newPasswordHint: "Naya Password (blank = change nahi)",
    loginPinHint: "same email+password wale users ke liye",
    enterNewPin: "Naya PIN daalo (blank = change nahi)",
    editRecordsRight: "Data edit karne ka right",
    deleteRecordsRight: "Data delete karne ka right",

    // ── Admin Settings ──
    imageTooLarge15: "Image 1.5MB se chhoti honi chahiye",
    passwordMismatch: "New password aur confirm password match nahi kar rahe",
    currentPasswordRequired: "Current password daalna zaroori hai",
    profileUpdated: "Profile update ho gayi!",
    profileUpdateError: "Update mein problem hui",
    fingerprintAlreadyRegistered: "Yeh fingerprint pehle se register hai!",
    fingerprintCancelled: "Fingerprint setup cancel ho gaya",
    fingerprintError: "Fingerprint setup mein error aaya",
    fingerprintSettingUp: "Setup ho raha hai...",
    registerFingerprint: "Fingerprint Register Karo",
    deleteFingerprintConfirm: "Purana fingerprint delete ho jaayega. Confirm?",
    fingerprintRemoved: "Purana fingerprint hata diya. Ab 'Register Karo' button se dobara add karo.",
    fingerprintResetError: "Reset mein problem aayi",
    resetReRegister: "Reset / Dobara Register Karo",
    fingerprintTimeoutHint: "Agar 'timed out' ya 'not allowed' error aa raha hai toh pehle Reset karo, phir dobara usi device/browser par register karo.",
    logoTooLarge500: "Logo 500KB se chhota hona chahiye",
    uploadPhoto: "Photo Upload Karo",
    changePhoto: "Photo Badlo",
    uploadLogo: "Logo Upload Karo",
    changeLogo: "Logo Badlo",
    mobileForLogin: "Mobile Number (Login ke liye use hoga)",
    mobileLoginHint: "Yahi number Tech Login mein daalenge",
    changePassword: "Password Badlein",
    leaveBlankMobileOnly: "(khali chhodein agar sirf mobile update karna ho)",
    oldPassword: "Purana password",
    newPasswordMin: "Naya password (min 6 char)",
    confirmNewPassword: "Dobara naya password",
    saveProfile: "Profile Save Karo",
    techLoginMyProfile: "Tech Login — Mera Profile",
    techLoginProfileDesc: "Tech Login ka mobile number aur password yahan se badlein.",
    fingerprintRegistered: "Fingerprint register ho gaya! Ab login page pe fingerprint se password list dekh sakte ho.",
    printFooterTitle: "Print Footer (Har Invoice / PDF Pe)",
    printFooterDesc: "Yeh text aur logo sabhi businesses ke har print/PDF ke neeche dikhayi dega.",
    printFooterLineHint: "Yeh line print mein sab se neeche aayegi",

    // ── Business Settings ──
    offlineDraftsFolderDesc: "Offline drafts is folder mein JSON file ke roop mein save honge",
    settingsSaved: "Settings save ho gayi!",
    firmIdentity: "Firm Identity (Invoice par dikhega)",
    voucherRedeemError: "Voucher redeem nahi hua",
    repairConfirm: "Yeh sab vouchers ke paidAmount aur status recalculate karega. Proceed?",
    vouchersFixed: "vouchers fix ho gaye",
    repairFailed: "Repair failed — console check karo",
    chooseFolder: "Folder Chuno",
    businessTypeInfo_pharmacy: "Invoice mein Drug License, Batch No, Expiry Date, MRP fields aayenge",
    businessTypeInfo_electronics: "Invoice mein Serial No, Model No, Brand, Warranty fields aayenge",
    businessTypeInfo_fabric: "Invoice mein Color, Design, Width, Composition fields aayenge",
    businessTypeInfo_restaurant: "Invoice mein Table No, Cover Count, Waiter Name fields aayenge",
    businessTypeInfo_auto_parts: "Invoice mein Vehicle Reg No, Vehicle Model, Part No fields aayenge",
    businessTypeInfo_jewellery: "Invoice mein Hallmark No, Purity, Weight, Making Charges fields aayenge",
    businessTypeInfo_construction: "Invoice mein Project Name, Work Order No, Site fields aayenge",
    businessTypeInfo_grocery: "Invoice mein Batch No, Expiry Date fields aayenge",
    businessTypeInfo_hardware: "Invoice mein Brand, Model No fields aayenge",
    showPrefix: "Prefix dikhao (SI, CN, PB, DN)",
    showPrefixSub: "Print mein SI/CN/PB/DN ka naam",
    showSeries: "Series number dikhao (1, 2, 3...)",
    showSeriesSub: "Sirf tab kaam karta hai jab series > 1 ho",
    showLeadingZeros: "Shuru ke zeros dikhao (0001 → 1)",
    showLeadingZerosSub: "OFF karne par 00005 ki jagah sirf 5 dikhega",

    // ── Super Admins ──
    allFieldsRequired: "Sab fields bharna zaroori hai",
    passwordMinChars: "Password kam se kam 6 characters ka hona chahiye",
    deleteSuperAdminConfirm: "Kya aap sure hain? Yeh super admin hata diya jayega.",
    newAdmin: "Naya Admin",
    superAdminDesc: "Super admin accounts jinhe poora system access hai",
    createNewSuperAdmin: "Naya Super Admin banayein",
    fullName: "Pura naam",
    atLeast6Chars: "Kam se kam 6 characters",
    noSuperAdminFound: "Koi super admin nahi mila",
    superAdminWarning: "Dhyan dein: Super admin ko poore platform ka access hota hai — sabhi businesses, settings, aur data. Sirf trusted tech support team members ko hi yahan add karein.",
    creating2: "Ban raha hai...",
    createBtn: "Banayein",

    // ── Voucher Bin ──
    binPageDesc: "Delete kiye hue vouchers — restore ya permanently delete karo",
    voucherRestored: "Voucher restore ho gaya!",
    voucherPermanentlyDeleted: "Voucher permanently delete ho gaya.",
    binEmpty: "Bin khali hai",
    binEmptyDesc: "Koi deleted document nahi hai",
    binHasDocuments: "document(s) bin mein hain. Restore karo wapas lane ke liye, ya permanently delete karo (undo nahi hoga).",
    permanentlyDeleteConfirm: "Permanently delete karo?",
    yesDelete: "Haan, Delete",

    // ── Offline Drafts ──
    offlineDraftsDesc: "Internet nahi tha tab save hue — ab submit karo",
    noPendingDrafts: "Koi pending draft nahi hai",
    allDataSubmitted: "Sab data submit ho chuka hai",
    goToDashboard: "Dashboard par jao",
    submitAll: "Sab Submit Karo",
    submittedToServer: "Server par submit ho gaya",
    offlinePartyNotFound: 'Party server par nahi mili. Pehle party banao phir submit karo.',
    partyIdNotResolved: "Party ka ID resolve nahi hua. 'Sab Submit Karo' use karo ya draft delete karke naya banao.",
    offlinePartyTip: "Kuch vouchers mein party offline banayi gayi thi. Sab Submit Karo use karo — yeh sahi order mein submit karta hai.",

    // ── Tech Login ──
    techLoginError: "Phone ya password galat hai",
    techForgotError: "Kuch problem ho gaya — dobara try karo",
    techStaffOnly: "Sirf authorized staff ke liye",
    mobileOrEmail: "Mobile ya email",
    forgotPassword: "Password bhool gaye?",
    loginBtn: "Login Karo",
    goToBusinessLogin: "← Business Login pe jaao",
    resetTechPassword: "Tech staff ka password reset karo",
    registeredMobileHint: "Jo mobile/email account se linked hai woh daalo",
    chooseNewPassword: "Naya password choose karo",
    resetPasswordBtn: "Password Reset Karo",
    goToLoginPage: "Login Page pe jaao",
    passwordResetSuccess: "Password reset ho gaya!",
    loginInProgress: "Login ho raha hai...",

    // ── Trial Banner ──
    trialEnded: "Trial Khatam Ho Gaya",
    trialEndedDesc: "Aapka trial period khatam ho chuka hai. Software continue karne ke liye plan activate karein.",
    contactTechSupport: "Tech Support Se Contact Karein",
    graceWarning: "din baad software lock ho jayega!",
    graceWarning2: "Abhi plan activate karein.",
    viewPlans: "Plan Dekhein",
    trialExpiredBanner: "Trial period khatam ho gaya — plan activate karo aur unlimited access pao!",
    gracePeriod: "30 Days Grace Period —",

    // ── Referral Banner ──
    referralRewardEarned: "Referral Reward Mila!",
    referralsCompleted: "referrals poore hue — Referral Plan aapke account pe activate ho gaya hai!",
    moreReferrals: "aur referral karo → ek aur reward!",

    // ── Subscription ──
    currentPlanBadge: "Aapka Current Plan",
    perMonth: "/mahina",
    perYear: "/saal",
    daysValidity: "din validity",
    invoicesPerMonth: "invoices/mahina",
    inTrial: "Trial period mein",
    paidPlanActive: "Paid plan active",
    shareCode: "Share karo",
    register5: "5 log register karein",
    theyEnterCode: "Woh aapka code daalein registration mein",
    getReferralPlan: "Referral Plan milega!",
    planAutoActivate: "Aapka plan auto-activate — congratulations!",
    voucherRedeemFailed: "Voucher redeem nahi hua",

    // ── Activity ──
    allLoginsDesc: "Sabhi logins, active users, aur GPS location",
    timeAgoSuffix: "pehle",

    // ── Admin Vouchers ──
    cancelVoucherConfirm: "Is voucher ko cancel karna chahte hain?",
    buyerCodeInstructions: "Yeh codes buyer ko de do. Buyer apne software mein 'Mera Plan' page pe code daalega.",
    deleteAll: "Saare Delete Karo",
    selectPlanFolder: "Baayein taraf se plan folder chunein",
    noVouchersInFolder: "Is folder mein koi voucher nahi",
    max50AtOnce: "Max 50 ek baar mein",
    afterPlanActivation: "Plan activate hone ke baad",
    sellingPriceNote: "Buyer se kitna liya — record ke liye",
    vouchersGenerated: "voucher(s) generate ho gaye!",
    voucherEditTitle: "Voucher Edit Karo",
    validityDaysNote: "Plan activate hone ke baad kitne din chalega",

    // ── Admin Businesses ──
    searchPartyPlaceholder: "Party ka naam search karo...",
    selectPartyFirst: "Party select karo pehle",
    deletePartyTransactions: "ke transactions delete karo",
    howManyDaysToAdd: "Kitne din add karne hain?",
    days: "din",
    daysAddedSuccess: "din successfully add ho gaye!",
    bonusDaysAlready: "Pehle se bonus days mila hai",
    cleanupOnlyVouchersPayments: "sirf vouchers aur payments delete honge. Customers, suppliers, items, units, tax rates safe rahenge.",
    cleanupFullBusiness: "Puri Business Clean",
    cleanupOneParty: "Ek Party Clean",
    cleanupDone: "Cleanup ho gaya!",
    cleanupWillDelete: "Ye delete hoga:",
    typeDeleteToConfirm: 'Confirm karne ke liye "DELETE" type karein',
    cleanAllData: "Sab Clean Karo",
    noPartyFound: "Koi party nahi mila",
    selectPartyToClean: "Neeche se party select karo — sirf usi party ke vouchers aur payments delete honge.",
    noUsersInBusiness: "Koi user nahi hai is business mein",
    assignRights: "Rights assign karein",
    perPlanModules: "(plan ke hisaab se available modules)",
    allModules: "(saare modules)",

    // ── Business / Admin Settings ──
    removeFolderBtn: "Hatao",
    changeFolderBtn: "Badlo",
    offlineDraftsChromeOnly: "Offline folder save sirf Chrome/Edge desktop par kaam karta hai. Mobile par drafts localStorage mein save hote hain.",
    offlineDataFolder: "Offline Data Folder",
    logoTooLarge500kb: "Logo 500KB se chhota hona chahiye",
    fingerprintSetupDesc: "Apna fingerprint register karo — phir login page pe bina password ke sirf fingerprint se saare users ke passwords dekh sakte ho.",
    voucherEditCurrentStatus: "Current status:",
    repairVouchersBtn: "Voucher Balances Recalculate Karo",

    // ── Admin Users ──
    passwordMin4: "Kam se kam 4 characters ka password daalen",
    passwordResetDone: "Password reset ho gaya ✓",

    // ── API / Session ──
    sessionInvalidated: "Aapka session kisi aur jagah se login ki wajah se band ho gaya. Dobara login karein.",

    // ── locationStore ──
    gpsNotSupported: "GPS is apke browser mein support nahi hai",
    gpsAccessDenied: "GPS access deny kiya — manually type karo",
  },
};

export function t(key: string, lang?: Lang): string {
  const l = lang || getLang();
  return T[l][key] || T.en[key] || key;
}
